// Generated by wxt
export {}
declare global {
  const ChatRole: typeof import('/Users/mac/Desktop/open-source/Syncia/src/hooks/useCurrentChat')['ChatRole']
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern']
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern']
  const MigrationError: typeof import('wxt/storage')['MigrationError']
  const browser: typeof import('wxt/browser')['browser']
  const createIframeUi: typeof import('wxt/client')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi']
  const defineAppConfig: typeof import('wxt/sandbox')['defineAppConfig']
  const defineBackground: typeof import('wxt/sandbox')['defineBackground']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/sandbox')['defineWxtPlugin']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const getFromIndexedDB: typeof import('/Users/mac/Desktop/open-source/Syncia/src/hooks/useStorage')['getFromIndexedDB']
  const getStoredChatKey: typeof import('/Users/mac/Desktop/open-source/Syncia/src/hooks/useCurrentChat')['getStoredChatKey']
  const injectScript: typeof import('wxt/client')['injectScript']
  const readStorage: typeof import('/Users/mac/Desktop/open-source/Syncia/src/hooks/useStorage')['readStorage']
  const saveToIndexedDB: typeof import('/Users/mac/Desktop/open-source/Syncia/src/hooks/useStorage')['saveToIndexedDB']
  const setStorage: typeof import('/Users/mac/Desktop/open-source/Syncia/src/hooks/useStorage')['setStorage']
  const storage: typeof import('wxt/storage')['storage']
  const useAppConfig: typeof import('wxt/client')['useAppConfig']
  const useChatCompletion: typeof import('/Users/mac/Desktop/open-source/Syncia/src/hooks/useChatCompletion')['useChatCompletion']
  const useChatHistory: typeof import('/Users/mac/Desktop/open-source/Syncia/src/hooks/useChatHistory')['useChatHistory']
  const useChatModels: typeof import('/Users/mac/Desktop/open-source/Syncia/src/hooks/useChatModels')['useChatModels']
  const useCurrentChat: typeof import('/Users/mac/Desktop/open-source/Syncia/src/hooks/useCurrentChat')['useCurrentChat']
  const useMessageDraft: typeof import('/Users/mac/Desktop/open-source/Syncia/src/hooks/useMessageDraft')['useMessageDraft']
  const usePrompts: typeof import('/Users/mac/Desktop/open-source/Syncia/src/hooks/usePrompts')['usePrompts']
  const useSettings: typeof import('/Users/mac/Desktop/open-source/Syncia/src/hooks/useSettings')['useSettings']
  const useStorage: typeof import('/Users/mac/Desktop/open-source/Syncia/src/hooks/useStorage')['useStorage']
  const useThemeSync: typeof import('/Users/mac/Desktop/open-source/Syncia/src/hooks/useThemeSync')['default']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ChatRole, ChatMessage } from '/Users/mac/Desktop/open-source/Syncia/src/hooks/useCurrentChat'
  import('/Users/mac/Desktop/open-source/Syncia/src/hooks/useCurrentChat')
  // @ts-ignore
  export type { MessageFile, MessageDraft } from '/Users/mac/Desktop/open-source/Syncia/src/hooks/useMessageDraft'
  import('/Users/mac/Desktop/open-source/Syncia/src/hooks/useMessageDraft')
  // @ts-ignore
  export type { PromptWithChildren, Prompt } from '/Users/mac/Desktop/open-source/Syncia/src/hooks/usePrompts'
  import('/Users/mac/Desktop/open-source/Syncia/src/hooks/usePrompts')
  // @ts-ignore
  export type { StorageArea } from '/Users/mac/Desktop/open-source/Syncia/src/hooks/useStorage'
  import('/Users/mac/Desktop/open-source/Syncia/src/hooks/useStorage')
}
